service: benbjurstrom

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    stage: 'prod'
    apiGateway:
      binaryMediaTypes:
        - 'image/webp'
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        APP_NAME: benbjurstrom
        APP_DEBUG: true
        SESSION_DRIVER: array
        CACHE_STORE: array
        BREF_BINARY_RESPONSES: '1'

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-83-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
          - ${bref-extra:gd-php-83}
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-83-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
  - serverless-lift

constructs:
    website:
        domain: benbjurstrom.com
        certificate: arn:aws:acm:us-east-1:221576664686:certificate/67c7fb10-bce7-4904-b109-cfdd99fbb8c0
        type: server-side-website
        assets:
          '/build/*': public/build
          '/favicon/*': public/favicon
          '/favicon.ico': public/favicon.ico
          '/ogimage.png': public/ogimage.png
          '/robots.txt': public/robots.txt
          '/prezet_sitemap.xml': public/prezet_sitemap.xml
          # add here any file or directory that needs to be served from S3
